# Generated by Django 6.0.3 on 2026-04-06 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this vault entry.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="User-defined label for this entry (stored in plaintext for UX).",
                        max_length=255,
                    ),
                ),
                (
                    "ciphertext",
                    models.TextField(
                        help_text="Base64-encoded AES-256-GCM ciphertext blob."
                    ),
                ),
                (
                    "iv",
                    models.CharField(
                        help_text="Base64-encoded initialization vector used for encryption.",
                        max_length=64,
                    ),
                ),
                (
                    "salt",
                    models.CharField(
                        help_text="Base64-encoded PBKDF2 salt used for key derivation.",
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this vault entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vault Entry",
                "verbose_name_plural": "Vault Entries",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-updated_at"], name="idx_user_updated"
                    )
                ],
            },
        ),
    ]
